force-app/main/default/objects/AnyAsciiMapping__c/AnyAsciiMapping__c.object-meta.xml
<CustomObject>
    <description>Many older systems do not accept foreign unicode characters. This object and invocable action attempt to &quot;transliterate&quot; strings into their American English equivalent.</description>
    <label>AnyAscii Mapping</label>
    <nameField>
        <displayFormat>ASCII-{00000000}</displayFormat>
        <label>AnyAscii Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnyAscii Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AnyAsciiMapping__c/fields/CodePoint__c.field-meta.xml
<CustomField>
    <fullName>CodePoint__c</fullName>
    <externalId>true</externalId>
    <label>Code Point</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AnyAsciiMapping__c/fields/InputValue__c.field-meta.xml
<CustomField>
    <fullName>InputValue__c</fullName>
    <inlineHelpText>This field is set automatically by a trigger when Code Point is populated. Not used by the system to perform string conversions.</inlineHelpText>
    <label>Unicode Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnyAsciiMapping__c/fields/IsBlankSpace__c.field-meta.xml
<CustomField>
    <fullName>IsBlankSpace__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, the Unicode input is replaced with a single space (U+0020).</inlineHelpText>
    <label>Blank Space</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AnyAsciiMapping__c/fields/OutputValue__c.field-meta.xml
<CustomField>
    <fullName>OutputValue__c</fullName>
    <label>ASCII Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnyAsciiMappingTest.cls
@isTest
private class AnyAsciiMappingTest {
    
    static testMethod void asciiTest() {
        AnyAsciiAction.Request req = new AnyAsciiAction.Request();
        req.inputString = 'Hello world';
        Assert.areEqual(
            req.inputString,
            AnyAsciiAction.execute(
                new List<AnyAsciiAction.Request>{req}
            )[0].outputString,
            'ASCII input value was modified.'
        );
    }

    static testMethod void blankSpaceTest() {
        // Non-breaking space is treated as 2 characters in some systems.
        AnyAsciiMapping__c mp = new AnyAsciiMapping__c(
            IsActive__c = true,
            IsBlankSpace__c = true,
            CodePoint__c = '160'
        );
        insert mp;
        AnyAsciiAction.Request req = new AnyAsciiAction.Request();
        req.inputString = '  Hello' + String.fromCharArray(new List<Integer>{160}) + 'world  ';
        List<AnyAsciiAction.Response> rs = AnyAsciiAction.execute(new List<AnyAsciiAction.Request>{req});
        Assert.areEqual(rs[0].outputString, 'Hello world');
    }

    static testMethod void emojiTest() {
        AnyAsciiMapping__c mp = new AnyAsciiMapping__c(
            IsActive__c = true,
            CodePoint__c = '129398',
            OutputValue__c = ':cold_face:'
        );
        insert mp;
        // Surrogates have been separated and code point re-calculated
        mp = [SELECT Id, CodePoint__c, InputValue__c FROM AnyAsciiMapping__c WHERE Id = :mp.Id];
        Assert.AreEqual('🥶', mp.InputValue__c, 'Trigger did not set InputValue__c to the Unicode of ' + mp.CodePoint__c);    
        AnyAsciiAction.Request req = new AnyAsciiAction.Request();
        req.inputString = '🥶 🥶';
        List<AnyAsciiAction.Response> rs = AnyAsciiAction.execute(new List<AnyAsciiAction.Request>{req});
        Assert.areEqual(rs[0].outputString, ':cold_face: :cold_face:');
    }

    static testMethod void hiddenCharTest() {
        // Zero-width space
        AnyAsciiMapping__c mp = new AnyAsciiMapping__c(
            IsActive__c = true,
            CodePoint__c = '8203'
        );
        insert mp;
        AnyAsciiAction.Request req = new AnyAsciiAction.Request();
        req.inputString = 'VP of Sales' + String.fromCharArray(new List<Integer>{8203});
        Assert.isFalse(req.inputString.isAsciiPrintable(), 'Value should contain a non-printable character.');
        List<AnyAsciiAction.Response> rs = AnyAsciiAction.execute(new List<AnyAsciiAction.Request>{req});
        Assert.areEqual(rs[0].outputString, 'VP of Sales');
    }
}